### Register
POST http://localhost:3000/register
Content-Type: application/x-www-form-urlencoded

name=ulul&email=ululazmi@gmail.com&password=123456Ua


### Login
POST http://localhost:3000/login
Content-Type: application/x-www-form-urlencoded

email=Ulull@gmail.com&password=123456Ua


### Update User
PUT http://localhost:3000/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODQxOTY0NjksInN1YiI6M30.9HPRvqJHtOAP8rF2UET1LGZ6HFTJxea0R5MyHQEWQgs

{
    "name" : "Ulul Azmi",
    "email" : "Ulull@gmail.com",
    "password" : "123456Ua"
}


### Delete User
DELETE http://localhost:3000/user
Accept: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODQxOTY0NjksInN1YiI6M30.9HPRvqJHtOAP8rF2UET1LGZ6HFTJxea0R5MyHQEWQgs


### create event
POST http://localhost:3000/user/event
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODQxOTY0NjksInN1YiI6M30.9HPRvqJHtOAP8rF2UET1LGZ6HFTJxea0R5MyHQEWQgs

{
    "name" : "Studi Kasus golang",
    "description" : "Implementasi hasil belajar selama ini",
    "location" : "rumah",
    "date_time" : "2026-07-20T09:30:00+07:00"
}

### update event 
PUT  http://localhost:3000/user/event/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODQxOTU5NjMsInN1YiI6M30.J2W0xUXswkXsIBiyN5C5FN9W0S6OJqpK8rtLmE2QOmA

{
    "name" : "Studi Kasus go-auth-jwt",
    "description" : "Implementasi hasil belajar selama ini",
    "location" : "Lueng bata",
    "date_time" : "2026-07-20T09:30:00+07:00"
}

### findBy id
GET  http://localhost:3000/user/event/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODQxOTU5NjMsInN1YiI6M30.J2W0xUXswkXsIBiyN5C5FN9W0S6OJqpK8rtLmE2QOmA


### find All
GET  http://localhost:3000/user/event
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODQxOTU5NjMsInN1YiI6M30.J2W0xUXswkXsIBiyN5C5FN9W0S6OJqpK8rtLmE2QOmA


### Delete
DELETE http://localhost:3000/user/event/3
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODQxOTU5NjMsInN1YiI6M30.J2W0xUXswkXsIBiyN5C5FN9W0S6OJqpK8rtLmE2QOmA
