### Register
POST http://localhost:3000/register
Content-Type: application/x-www-form-urlencoded

name=ulul&email=ulul@gmail.com


### Login
POST http://localhost:3000/login
Content-Type: application/x-www-form-urlencoded

email=uluaal@gmail.com&password=123456Uaa