// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"GO-AUTH-JWT/app"
	"GO-AUTH-JWT/controller"
	"GO-AUTH-JWT/repository"
	"GO-AUTH-JWT/service"
	"GO-AUTH-JWT/storage"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializedServer() *app.Server {
	fiberApp := app.NewServer()
	repositoryUserRepository := repository.NewUserRepository()
	db := app.OpenConnection()
	v := _wireValue
	validate := validator.New(v...)
	authService := service.NewAuthService(repositoryUserRepository, db, validate)
	authController := controller.NewAuthController(authService)
	userService := service.NewUserService(repositoryUserRepository, db, validate)
	userController := controller.NewUserController(userService)
	eventRepository := repository.NewEventRepository()
	client := storage.InitImageKit()
	uploader := storage.NewImagekitUploader(client)
	eventService := service.NewEventService(eventRepository, db, uploader, validate)
	eventController := controller.NewEventController(eventService)
	server := app.BuildServer(fiberApp, authController, userController, eventController)
	return server
}

var (
	_wireValue = []validator.Option{}
)

// injector.go:

var userRepository = repository.NewUserRepository

var authSet = wire.NewSet(service.NewAuthService, controller.NewAuthController)

var userSet = wire.NewSet(service.NewUserService, controller.NewUserController)

var eventSet = wire.NewSet(repository.NewEventRepository, service.NewEventService, storage.NewImagekitUploader, storage.InitImageKit, controller.NewEventController)
